{{- if .Release.IsInstall -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-secret
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  secret: {{ randAlphaNum 64 | b64enc }}
{{- end }}
