{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
data:
  database.yml.erb: |
    production:
      adapter: postgresql
      encoding: unicode
      database: {{ default "gitlabhq_production" .Values.psql.database | quote }}
      pool: 10
      username: {{ default "gitlab" .Values.psql.username | quote }}
      password: <%= File.read("/etc/gitlab/postgres/psql-password") %>
      host: {{ template "unicorn.psql.host" . }}
      port: {{ default 5432 .Values.psql.port }}
      # load_balancing:
      #   hosts:
      #     - host1.example.com
      #     - host2.example.com
  resque.yml.erb: |
    production:
      # Redis (single instance)
      url: redis://:<%= File.read("/etc/gitlab/redis/password") %>@{{ template "unicorn.redis.host" . }}:{{ default 6379 .Values.redis.port }}
  workhorse-config.toml.erb: |
    [redis]
    URL = "tcp://{{ template "unicorn.redis.host" . }}:{{ default 6379 .Values.redis.port }}"
    Password = "<%= File.read("/etc/gitlab/redis/password") %>"
  unicorn.rb: |
    worker_processes {{ .Values.workerProcesses }}
    working_directory "/home/git/gitlab"
    listen "0.0.0.0:{{ .Values.service.internalPort }}", :tcp_nopush => true
    timeout {{ .Values.workerTimeout }}
    pid "/home/git/unicorn.pid"
    preload_app true

    before_fork do |server, worker|
      old_pid = "#{server.config[:pid]}.oldbin"
      if old_pid != server.pid
        begin
          sig = (worker.nr + 1) >= server.worker_processes ? :QUIT : :TTOU
          Process.kill(sig, File.read(old_pid).to_i)
        rescue Errno::ENOENT, Errno::ESRCH
        end
      end

      ActiveRecord::Base.connection.disconnect! if defined?(ActiveRecord::Base)
    end

    after_fork do |server, worker|
      ActiveRecord::Base.establish_connection if defined?(ActiveRecord::Base)
      defined?(::Prometheus::Client.reinitialize_on_pid_change) && Prometheus::Client.reinitialize_on_pid_change
    end

    ENV['GITLAB_UNICORN_MEMORY_MIN'] = (400 * 1 << 20).to_s
    ENV['GITLAB_UNICORN_MEMORY_MAX'] = (650 * 1 << 20).to_s
  gitlab.yml.erb: |
    production: &base
      gitlab:
        host: {{ template "gitlabHost" . }}
        https: {{ hasPrefix "https://" (include "gitlabUrl" .) }}
        trusted_proxies:
        email_from: example@example.com
        email_display_name: GitLab
        email_reply_to: noreply@example.com
        email_subject_suffix: ''
        default_projects_features:
          issues: true
          merge_requests: true
          wiki: true
          snippets: true
          builds: true
          container_registry: true
      incoming_email:
        enabled: false
      artifacts:
        enabled: true
      lfs:
        enabled: false
        object_store:
          enabled: false
      pages:
        enabled: false
      mattermost:
        enabled: false
      gravatar:
      gitlab_ci:
      ldap:
        enabled: false
      kerberos:
        enabled: false
      omniauth:
        enabled: false
      shared:
      gitaly:
        client_path: /home/git/gitaly/bin
        token: "<%= File.read('/etc/gitlab/gitaly/gitaly_token') %>"
      repositories:
        storages: # You must have at least a `default` storage path.
          default:
            path: /var/opt/gitlab/repo
            gitaly_address: tcp://{{ template "unicorn.gitaly.host" . }}:{{ default 8075 .Values.gitaly.port }}
      backup:
        path: "tmp/backups"   # Relative paths are relative to Rails.root (default: tmp/backups/)
      gitlab_shell:
        path: /home/git/gitlab-shell/
        hooks_path: /home/git/gitlab-shell/hooks/
        secret_file: /etc/gitlab/shell/.gitlab_shell_secret
        upload_pack: true
        receive_pack: true
      workhorse:
      git:
        bin_path: /usr/bin/git
      webpack:
      monitoring:
        ip_whitelist:
          - 127.0.0.0/8
        sidekiq_exporter:
      extra:
      rack_attack:
        git_basic_auth:
      ## Registry Integration
      registry:
        enabled: true
        host: {{ template "unicorn.registry.host" . }}
        {{- if .Values.registry.port }}
        port: {{ .Values.registry.port }}
        {{- end }}
        api_url: {{ default "http" .Values.registry.api.protocol }}://{{ template "unicorn.registry.api.host" . }}:{{ default 5000 .Values.registry.api.port }}
        key: /etc/gitlab/registry/gitlab-registry.key
        issuer: {{ .Values.registry.tokenIssuer }}
  configure: |
    set -e
    mkdir -p /init-secrets/redis /init-secrets/shell /init-secrets/gitaly \
      /init-secrets/registry /init-secrets/postgres
    cp /init-config/redis/password /init-secrets/redis/password
    cp /init-config/shell/.gitlab_shell_secret /init-secrets/shell/.gitlab_shell_secret
    cp /init-config/gitaly/gitaly_token /init-secrets/gitaly/gitaly_token
    cp /init-config/registry/gitlab-registry.key /init-secrets/registry/gitlab-registry.key
    cp /init-config/postgres/psql-password /init-secrets/postgres/psql-password
# Leave this here - This line denotes end of block to the parser.
{{- end }}
