{{/* Very conservative. Only let one of any of the sentinal/server pods be down */}}
{{- if .Values.enabled -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "fullname" . }}
  labels:
{{ include "labels.standard" . | indent 4 }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
{{ include "labels.standard" . | indent 6 }}
{{- end -}}
