{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "migrations.fullname" . }}
  labels:
    app: {{ template "migrations.fullname" . }}
data:
  database.yml: |
    production:
      adapter: postgresql
      encoding: unicode
      database: {{ default "gitlabhq_production" .Values.psql.database | quote }}
      pool: 10
      username: {{ default "gitlab" .Values.psql.username | quote }}
      password: {{ .Values.psql.password | quote }}
      host: {{ template "migrations.psql.host" . }}
      port: {{ default 5432 .Values.psql.port }}
      # load_balancing:
      #   hosts:
      #     - host1.example.com
      #     - host2.example.com
  resque.yml.erb: |
    production:
      # Redis (single instance)
      url: redis://:<%= File.read("/etc/gitlab-redis/password") %>@{{ template "migrations.redis.host" . }}:{{ default 6379 .Values.redis.port }}
  gitlab.yml: |
    production: &base
      gitlab:
      repositories:
        storages:
          default:
            path: /var/opt/gitlab/repo
            gitaly_address: tcp://localhost:8075

# Leave this here - This line denotes end of block to the parser.
{{- end }}
