---
apiVersion: v1
name: gitlab
version: 0.1.0
appVersion: master
description: Web-based Git-repository manager with wiki and issue-tracking
  features, using an open-source license.
keywords:
- gitlab
home: https://about.gitlab.com/
icon: https://upload.wikimedia.org/wikipedia/commons/1/18/GitLab_Logo.svg
sources:
- https://gitlab.com/charts/gitlab
maintainers:
- name: GitLab Inc.
  email: support@gitlab.com
