dependencies:
- name: cert-manager
  version: 0.2.2
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: certmanager.install
  alias: certmanager
- name: prometheus
  version: 5.5.3
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: prometheus.install
- name: postgresql
  version: 0.10.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: postgresql.install
