# Default values for gitlab-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nginx:
  ingress:
    enabled: true
    hosts:
      - name: registry.example.local
        serviceName: registry
        servicePort: registry
      - name: gitlab.example.local
        serviceName: omnibus
        servicePort: og-workhorse

registry:
  enabled: false

redis:
  enabled: false

gitlab:
  omnibus:
    enabled: false
  unicorn:
    enabled: false
  gitlab-shell:
    enabled: false

## Global configuration items
global:
  ## Configuration
  # domain: Top-Level Domain for deployment
  ## Feature gating
  # emptyDir.sizeLimit is alpha in Kubernetes v1.7.x, standard in v1.8.x
  # When available, it is used to limit the size of ephemeral data
  emptyDirLimits: true
