# Default values for gitlab-chart.
# This is a YAML-formatted file.

global:
  hosts:
    domain: example.local
    https: true

nginx:
  ingress:
    enabled: true
    acme: true

kube-lego:
  enabled: true
  config:
    LEGO_EMAIL: email@domain.tld
    LEGO_URL: https://acme-v01.api.letsencrypt.org/directory
  rbac:
    create: true

registry:
  enabled: false

minio:
  enabled: false

redis:
  enabled: false

gitlab:
  # Unicorn (and workhorse) chart
  unicorn:
    enabled: false
    registry:
      tokenIssuer: gitlab-issuer
      certificate:
        secret: gitlab-registry
        key: registry-auth.key
    shell:
      authToken:
        secret: gitlab-shell-secret
    gitaly:
      serviceName: gitaly
      authToken:
        secret: gitaly-secret
        key: token
    redis:
      serviceName: redis
      password:
        secret: gitlab-redis
        key: redis-password
    psql:
      password:
        secret: gitlab-postgres
  # Sidekiq chart, with split queues (see charts/gitlab/charts/sidekiq/values.yaml)
  sidekiq:
    enabled: false
    concurrency: 10
    timeout: 5
    gitaly:
      serviceName: gitaly
      authToken:
        secret: gitaly-secret
        key: token
    redis:
      serviceName: redis
      password:
        secret: gitlab-redis
        key: redis-password
    psql:
      password:
        secret: gitlab-postgres
  # Shell provides SSH access
  gitlab-shell:
    enabled: false
    unicorn:
      serviceName: unicorn
    redis:
      serviceName: redis
      password:
        secret: gitlab-redis
        key: redis-password
  # Gitaly provides storage & API access to Git repository data
  gitaly:
    enabled: false
    authToken:
      name: gitaly-secret
      key: token
  # Handle database init and upgrade migrations, via gitlab-rails codebase
  migrations:
    enabled: false
    initialRootPassword: "minikube"
    redis:
      serviceName: redis
      password:
        secret: gitlab-redis
        key: redis-password
    psql:
      password:
        secret: gitlab-postgres
  # omnibus sub-chart (development only)
  omnibus:
    enabled: false
    # use Redis chart
    redis:
      password:
        secret: gitlab-redis
        key: redis-password
    # provide PostgreSQL services
    psql:
      password:
        secret: gitlab-postgres
