# Default values for gitlab-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nginx:
  ingress:
    enabled: true
    hosts:
      - name: registry.example.local
        serviceName: registry
        servicePort: registry
      - name: gitlab.example.local
        serviceName: unicorn
        servicePort: workhorse

registry:
  enabled: false

redis:
  enabled: false

gitlab:
  omnibus:
    enabled: false
  unicorn:
    enabled: false
  gitlab-shell:
    enabled: false

global:
  gitlabHost:
    name: gitlab.example.local
    serviceName: unicorn
    servicePort: workhorse
  registryHost:
    name: registry.example.local
    serviceName: registry
    servicePort: registry
