{{/* This restricts disruptions to 1 over all sidekiq pods regardless of queue-pod-name */}}
{{- if .Values.enabled -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "fullname" . }}
  labels:
{{ include "gitlab.standardLabels" . | indent 4 }}
spec:
  maxUnavailable: {{ .Values.maxUnavailable }}
  selector:
    matchLabels:
{{ include "gitlab.immutableLabels" . | indent 6 }}
{{- end -}}
