{{- if .Values.enabled -}}
{{- $httpSecret := randAlphaNum 128 | b64enc -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
data:
  redis.conf: |
    # stay in foreground
    daemonize no
    # listen on all interfaces
    bind 0.0.0.0
    port {{ .Values.service.internalPort }}
    timeout {{ .Values.timeout }}
    tcp-keepalive {{ .Values.tcpKeepalive}}
    # Log level
    loglevel {{ .Values.loglevel }}
    # Log to stdout
    logfile ""
    # database count (picked from Omnibus' redis.conf)
    databases 16
    # NO PERSISTENCE DURING POC!
    save ""
    # save 900 1
    # save 300 10
    # save 60 10000
# leave this here. Signals end of block to the parser
{{- end -}}
