{{- if .Values.enabled -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "nginx-ingress.controller.fullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
{{ include "gitlab.standardLabels" . | indent 4 }}
    component: "{{ .Values.controller.name }}"
spec:
  selector:
    matchLabels:
{{ include "gitlab.immutableLabels" . | indent 6 }}
      component: "{{ .Values.controller.name }}"
  minAvailable: {{ .Values.controller.minAvailable }}
{{- end }}
