{{- if .Values.enabled -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
{{ include "gitlab.standardLabels" . | indent 4 }}
    component: "{{ .Values.defaultBackend.name }}"
  name: {{ template "nginx-ingress.defaultBackend.fullname" . }}
spec:
  selector:
    matchLabels:
{{ include "gitlab.immutableLabels" . | indent 6 }}
      component: "{{ .Values.defaultBackend.name }}"
  minAvailable: {{ .Values.defaultBackend.minAvailable }}
{{- end }}
