# Default values for sidekiq.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: registry.gitlab.com/gitlab-org/build/cng/gitlab-sidekiq-ee
  tag: latest
  pullPolicy: Always
enabled: true

metrics:
  enabled: true
  port: 3807
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3807"

redis:
  # host: '0.0.0.0'
  # port: 6379
  serviceName: 'redis'
  password:
    secret: gitlab-redis
    key: redis-password

global:
  psql: {}
    # host: '0.0.0.0'
    # port: '5432'
    # database: 'gitlabhq_production'
    # username: 'gitlab'
    # password:
    #   secret: gitlab-postgres
    #   key: psql-password
gitaly:
  # host: '0.0.0.0'
  # port: 8075
  serviceName: 'gitaly'
  authToken:
    secret: gitaly-secret
    key: token

# Global defaults
replicas: 1
railsSecrets:
  secret: rails-secrets
  key: secrets.yml
concurrency: 10
timeout: 5
resources:
  # limits:
  #  cpu: 500m
  #  memory: 1G
  requests:
    cpu: 500m
    memory: 1024M

# Define queue groups into Pods
pods:
  - name: all-in-1
    concurrency: 10
    replicas: 1
    queues:
      - [post_receive, 5]
      - [merge, 5]
      - [update_merge_requests, 3]
      - [process_commit, 3]
      - [new_note, 2]
      - [new_issue, 2]
      - [new_merge_request, 2]
      - [pipeline_processing, 5]
      - [pipeline_creation, 4]
      - [pipeline_default, 3]
      - [pipeline_cache, 3]
      - [pipeline_hooks, 2]
      - [gitlab_shell, 2]
      - [email_receiver, 2]
      - [emails_on_push, 2]
      - [mailers, 2]
      - [invalid_gpg_signature_update, 2]
      - [create_gpg_signature, 2]
      - [rebase, 2]
      - [upload_checksum, 1]
      - [repository_fork, 1]
      - [repository_import, 1]
      - [github_importer, 1]
      - [github_import_advance_stage, 1]
      - [project_service, 1]
      - [delete_user, 1]
      - [delete_merged_branches, 1]
      - [authorized_projects, 1]
      - [expire_build_instance_artifacts, 1]
      - [group_destroy, 1]
      - [irker, 1]
      - [namespaceless_project_destroy, 1]
      - [project_cache, 1]
      - [project_destroy, 1]
      - [project_export, 1]
      - [web_hook, 1]
      - [repository_check, 1]
      - [git_garbage_collect, 1]
      - [reactive_caching, 1]
      - [cronjob, 1]
      - [default, 1]
      - [pages, 1]
      - [system_hook_push, 1]
      - [update_user_activity, 1]
      - [propagate_service_template, 1]
      - [background_migration, 1]
      - [gcp_cluster, 1]
      - [project_migrate_hashed_storage, 1]
      - [storage_migrator, 1]
      - [pages_domain_verification, 1]
      - [object_storage_upload, 1]
      - [object_storage, 1]
      - [plugin, 1]
      - [pipeline_background, 1]
