nginx:
  ingress:
    enabled: true
    hosts:
      - name: registry.example.local
        serviceName: registry
        servicePort: registry
      - name: gitlab.example.local
        serviceName: unicorn
        servicePort: workhorse

# Registry sub-chart
registry:
  enabled: true
  registry:
    replicas: 1
    # https://docs.docker.com/registry/deploying/#storage-customization
    storage:
      filesystem:
        rootdirectory: '/var/lib/registry'
      cache:
        blobdescriptor: 'inmemory'
      delete:
        enabled: true
    authEndpoint: 'http://gitlab.example.local'
    tokenIssuer: omnibus-gitlab-issuer
    certBundle:
      secretName: 'gitlab-registry-certbundle'
      bundleName: 'gitlab-registry.crt'

# GitLab sub-chart
gitlab:
    unicorn:
      enabled: true
      gitlab_host: gitlab.example.local
      redis:
        password:
          secret: gitlab-redis
          key: redis-password
      psql:
        serviceName: omnibus
        password: secure-pgsql-password
    sidekiq:
      enabled: true
      concurrency: 10
      timeout: 5
      redis:
        password:
          secret: gitlab-redis
          key: redis-password
      psql:
        serviceName: omnibus
        password: secure-pgsql-password

    # omnibus sub-chart (development only)
    omnibus:
      enabled: true
      initial_root_password: "minikube"
      unicorn:
        enabled: false
      workhorse:
        enabled: false
      sidekiq:
        enabled: false
      redis:
        enabled: true
        password:
          secret: gitlab-redis
          key: redis-password
      psql:
        enabled: true
      registry:
        host: registry.example.local
        port: 80
        secret: omnibus-registry
        certificate: gitlab-registry.key
