nginx:
  ingress:
    enabled: true
    hosts:
      - name: registry.example.local
        serviceName: registry
        servicePort: registry
      - name: gitlab.example.local
        serviceName: unicorn
        servicePort: workhorse
  shell:
    name: gitlab-shell
    port: ssh

# Registry sub-chart
registry:
  enabled: true
  registry:
    replicas: 1
    # https://docs.docker.com/registry/deploying/#storage-customization
    storage:
      filesystem:
        rootdirectory: '/var/lib/registry'
      cache:
        blobdescriptor: 'inmemory'
      delete:
        enabled: true
    authEndpoint: 'http://gitlab.example.local'
    tokenIssuer: omnibus-gitlab-issuer
    certBundle:
      secretName: 'gitlab-registry-certbundle'
      bundleName: 'gitlab-registry.crt'

# GitLab sub-chart
gitlab:
    # Unicorn (and workhorse) chart
    unicorn:
      enabled: true
      gitlab_host: gitlab.example.local
      shell:
        secret: gitlab-shell-secret
      gitaly:
        auth_token: generatedAuthToken
      redis:
        serviceName: omnibus
        password:
          secret: gitlab-redis
          key: redis-password
      psql:
        serviceName: omnibus
        password: secure-pgsql-password
    # Sidekiq chart, with split queues (see charts/gitlab/charts/sidekiq/values.yaml)
    sidekiq:
      enabled: true
      concurrency: 10
      timeout: 5
      gitaly:
        auth_token: generatedAuthToken
      redis:
        serviceName: omnibus
        password:
          secret: gitlab-redis
          key: redis-password
      psql:
        serviceName: omnibus
        password: secure-pgsql-password

    gitlab-shell:
      enabled: true
      unicorn:
        serviceName: unicorn
      redis:
        serviceName: omnibus
        password:
          secret: gitlab-redis
          key: redis-password

    # omnibus sub-chart (development only)
    omnibus:
      enabled: true
      initial_root_password: "minikube"
      unicorn:
        enabled: false
      workhorse:
        enabled: false
      sidekiq:
        enabled: false
      shell:
        enabled: false
      gitaly:
        enabled: true
        auth_token: generatedAuthToken
      redis:
        enabled: true
        password:
          secret: gitlab-redis
          key: redis-password
      psql:
        enabled: true
        sql_user_password: ${echo -n '${secure-pgsql-password}gitlab' | md5sum - | cut -d ' ' -f1}
      registry:
        host: registry.example.local
        port: 80
        secret: omnibus-registry
        certificate: gitlab-registry.key
