# Default values for gitlab.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
ingress:
  enabled: false
  proxyBodySize: "512m"
  proxyReadTimeout: 600
  proxyConnectTimeout: 15
  acme: false
  # Used to create Ingress record (should used with service.type: ClusterIP).
  hosts: []
    # - name: prometheus.example.local
    #   serviceName: omnibus
    #   servicePort: prometheus
  annotations:
    # kubernetes.io/tls-acme: "true"
  tls:
    # Secrets must be manually created in the namespace.
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local

global:
  hosts:
    domain: example.local
    hostSuffix:
    https: false
    tls: {}
      # secretName:
    gitlab:
      #name: gitlab.example.local
      #https: false
      serviceName: unicorn
      servicePort: workhorse
      tls: {}
        # secretName:
    registry:
      #name: registry.example.local
      #https: false
      serviceName: registry
      servicePort: registry
      tls: {}
        # secretName:
      annotations: {}
        # kubernetes.io/tls-acme: "true"
      proxyBodySize: "0"
      proxyReadTimeout: 900
    minio:
      #name: minio.example.local
      #https: false
      serviceName: minio-svc
      servicePort: service
      tls: {}
        # secretName:
      annotations: {}
        # kubernetes.io/tls-acme: "true"
      proxyBodySize: "0"
      proxyReadTimeout: 900

gitaly:
  enabled: false
gitlab-shell:
  enabled: false
mattermost:
  enabled: false
migrations:
  enabled: false
omnibus:
  enabled: false
pages:
  enabled: false
sidekiq:
  enabled: false
unicorn:
  enabled: false
workhorse:
  enabled: false
