apiVersion: v1
description: Object storage server built for cloud applications and devops.
home: https://minio.io
icon: https://www.minio.io/img/logo_160x160.png
keywords:
- storage
- object-storage
- S3
maintainers:
- name: GitLab Inc.
  email: support@gitlab.com
- name: The Build Team
- email: hello@acale.ph
  name: Acaleph
- email: hello@minio.io
  name: Minio
name: minio
sources:
- https://gitlab.com/charts/helm.gitlab.io
- https://github.com/minio/minio
version: 0.4.3
