{{- if .Values.enabled -}}
{{- $secret := randAlphaNum 128 | b64enc -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
data:
  configure: |
    set -e

    # populate gitlab-secrets, /gitlab-secrets => /etc/gitlab-secrets
    mkdir -p /gitlab-secrets/redis /gitlab-secrets/postgres
    cp /init-secrets/redis/password  /gitlab-secrets/redis/password
    cp /init-secrets/postgres/psql-password  /gitlab-secrets/postgres/psql-password

    # populate gitlab-config, /gitlab-config => /etc/gitlab
    cp /config/gitlab.rb /gitlab-config/

    # pre-touch ssh_host_*_key. We don't use them in this chart, but this saves
    # time by not generating things we don't use.
    touch /gitlab-config/ssh_host_rsa_key
    touch /gitlab-config/ssh_host_ecdsa_key
    touch /gitlab-config/ssh_host_ed25519_key
    chown 0400 /gitlab-config/ssh_host_*
  gitlab.rb: |
    ###################
    # gitlab/gitlab-rails
    external_url {{ .Values.external_url | quote }}
    gitlab_rails['rake_cache_clear']= false
    # PostgresQL related
    gitlab_rails['auto_migrate'] = false
    gitlab_rails['db_host'] = '127.0.0.1'
    gitlab_rails['db_port'] = {{ default .Values.service.ports.psql .Values.psql.port }}
    gitlab_rails['db_username'] = {{ default "gitlab" .Values.psql.username | quote }}
    gitlab_rails['db_database'] = {{ default "gitlabhq_production" .Values.psql.database | quote }}
    # Redis related
    gitlab_rails['redis_host'] = {{ printf "%s-%s" .Release.Name .Values.redis.serviceName | quote }}
    gitlab_rails['redis_port'] = {{ default 6397 .Values.redis.port }}
    gitlab_rails['redis_database'] = {{ default 0 .Values.redis.database }}
    gitlab_rails['redis_password'] = File.read("/etc/gitlab-secrets/redis/password")
    ###################
    # PostgresQL
    postgresql['enable'] = true
    postgresql['listen_address'] = '0.0.0.0'
    postgresql['port'] = {{ .Values.service.ports.psql }}
    postgresql['shared_buffers'] = {{ .Values.psql.shared_buffers | quote }}
    postgresql['md5_auth_cidr_addresses'] = %w{{ .Values.trusted_proxies }}
    postgresql['trust_auth_cidr_addresses'] = ['127.0.0.1/24']
    postgresql['data_dir'] = "/postgresql/data"
    {{-   if .Values.psql.password }}
    postgresql['sql_user_password'] = Digest::MD5.hexdigest File.read("/etc/gitlab-secrets/postgres/psql-password") << {{ default "gitlab" .Values.psql.username | quote }}
    {{-   end }}
    ###################
    # DISABLED SERVICES
    redis['enable'] = false
    nginx['enable'] = false
    gitlab_workhorse['enable'] = false
    unicorn['enable'] = false
    sidekiq['enable'] = false
    gitaly['enable'] = false
    registry['enable'] = false
    registry_nginx['enable'] = false
    gitlab_pages['enable'] = false
    pages_nginx['enable'] = false
    mattermost['enable'] = false
    mattermost_nginx['enable'] = false
    prometheus['enable'] = false
# Leave this here - This line denotes end of block to the parser.
{{- end }}
