{{- if and .Values.global.minio.enabled .Values.defaultBuckets }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "minio.createBucketsJobName" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
{{ include "gitlab.standardLabels" . | indent 4 }}
spec:
  activeDeadlineSeconds: 600
  selector:
    matchLabels:
{{ include "gitlab.immutableLabels" . | indent 6 }}
      component: create-buckets
  template:
    metadata:
      labels:
{{ include "gitlab.standardLabels" . | indent 8 }}
        component: create-buckets
    spec:
      restartPolicy: OnFailure
    {{- if .Values.nodeSelector }}
      nodeSelector:
    {{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
      volumes:
        - name: minio-configuration
          projected:
            sources:
            - configMap:
                name: {{ template "minio.fullname" . }}-config-cm
            - secret:
                name: {{ template "gitlab.minio.credentials.secret" . }}
      containers:
      - name: minio-mc
        image: {{ .Values.minioMc.image }}:{{ .Values.minioMc.tag }}
        command: ["/bin/sh", "/config/initialize"]
        env:
          - name: MINIO_ENDPOINT
            value: {{ template "minio.fullname" . }}-svc
          - name: MINIO_PORT
            value: {{ .Values.servicePort | quote }}
        volumeMounts:
          - name: minio-configuration
            mountPath: /config
    {{- end }}
