{{- if .Values.enabled }}
kind: Service
apiVersion: v1
metadata:
  name: {{ template "minio.fullname" . }}
  labels:
    app: {{ template "minio.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.serviceType }}
  {{- if eq .Values.serviceType "LoadBalancer" }}
  loadBalancerIP: {{ default "" .Values.minioLoadBalancerIP }}
  {{- end }}
  selector:
    app: {{ template "minio.fullname" . }}
  ports:
    - name: service
      port: 9000
      targetPort: {{ .Values.servicePort }}
      protocol: TCP
{{- end }}
