{{- if and .Values.enabled .Values.defaultBuckets }}
apiVersion: v1
kind: Pod
metadata:
  name: {{ template "minio.fullname" . }}-create-bucket
  labels:
    app: {{ template "minio.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  restartPolicy: OnFailure
{{- if .Values.nodeSelector }}
  nodeSelector:
{{ toYaml .Values.nodeSelector | indent 4 }}
{{- end }}
  volumes:
    - name: minio-user
      secret:
        secretName: {{ template "minio.fullname" . }}-user
  containers:
  - name: minio-mc
    image: minio/mc
    command: ["/bin/sh", "-c",
    "/usr/bin/mc config host add myminio http://$MINIO_ENDPOINT:9000 $(cat /secrets/accesskey) $(cat /secrets/secretkey);
    {{- range $bucket := .Values.defaultBuckets }}
    {{-   if default false .purge | eq true }}
    /usr/bin/mc rm -r --force myminio/{{ .name }};
    {{-   end }}
    /usr/bin/mc mb myminio/{{ .name }};
    /usr/bin/mc policy {{ default "none" .policy }} myminio/{{ .name }};
    {{- end }}"]
    env:
      - name: MINIO_ENDPOINT
        value: {{ template "minio.fullname" . }}-svc
    volumeMounts:
      - name: minio-user
        mountPath: /secrets
{{- end }}
