{{- if .Values.enabled -}}
{{- $httpSecret := randAlphaNum 128 | b64enc -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
data:
  http.addr: :{{ .Values.service.internalPort }}
  http.secret: {{ default $httpSecret .Values.registry.httpSecret | quote }}
  auth.token.realm: {{ .Values.registry.authEndpoint }}/jwt/auth
  auth.token.service: {{ .Values.registry.tokenService | quote }}
  auth.token.issuer: {{ .Values.registry.tokenIssuer | quote }}
  auth.token.rootcertbundle: "/etc/registry-secret/{{ .Values.registry.certBundle.bundleName }}"
{{- end -}}
