apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: {{ .Release.Name }}-issuer
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
spec:
  acme:
    # The ACME server URL
    server: {{ .Values.certmanager.issuer.server | quote }}
    # Email address used for ACME registration
    email: {{ required "You must provide an email to associate with your TLS certificates. Please set certmanager.issuer.email" .Values.certmanager.issuer.email | quote }}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: {{ .Release.Name }}-acme-key
    # Enable the HTTP-01 challenge provider
    http01: {}
