{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.psql }}
      targetPort: {{ .Values.service.ports.psql }}
      protocol: TCP
      name: og-psql
  selector:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
{{- end }}
